import { pluralEn } from "./plural";
import type { Catalog } from "./types";

/** English copy: short and complete, so a locale switch never shows holes. */
export const en: Catalog = {
  time: {
    weekdaysShort: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    minutes: "min",
    hours: "h",
    today: "today",
    tomorrow: "tomorrow",
    date: (day, month, year) => (year === null ? `${month} ${day}` : `${month} ${day}, ${year}`),
    onDate: (weekday, date) => `${weekday}, ${date}`,
  },
  units: {
    blocks: (count) => `${count} ${pluralEn(count, "block", "blocks")}`,
  },
  common: {
    quoted: "“{text}”",
    otherTime: "Other time",
    edit: "Edit",
    selected: "✓ {label}",
    tryInline: "Free time today",
    tryInlineQuery: "free time today",
    openMiniApp: "Open planner",
  },
  welcome: {
    greeting: "Hi!",
    greetingNamed: "Hi, {name}!",
    intro: "I find time for your tasks and put it in your calendar.",
    ways: [
      "Write a task, for example “prepare the deck by Friday, about two hours”",
      "Forward a message and I will suggest what to do with it",
      "In a group, reply to a message and mention me — I will find time for you only",
    ],
    calendarHint: "Your calendar is not connected yet. Connect it and I will avoid your busy hours.",
    connectCalendar: "📅 Connect calendar",
    profileButton: "⚙️ Set up profile",
    calendarConnectedNote: "Calendar connected ✓",
    providersTitle: "Which calendar should I connect?",
    back: "‹ Back",
    providers: [
      { id: "google", label: "📆 Google" },
      { id: "yandex", label: "🗓 Yandex" },
      { id: "outlook", label: "📧 Outlook" },
      { id: "apple", label: "🍎 Apple" },
    ],
    legal: "By continuing to use this bot you agree to the {doc1} and the {doc2}.",
    legalDoc1: "document 1",
    legalDoc2: "document 2",
  },
  help: {
    title: "What I can do",
    items: [
      "Personal tasks: tell me what needs doing and I will suggest time and book a block in your calendar.",
      "Forwarded messages: I work out whether it is a meeting, a task or just information.",
      "Groups: reply to a message and mention me. I find time for you only and never show calendar details in the group.",
    ],
    inlineHint: "Quick access: in any chat type {bot} and the words “free time”.",
    commandsTitle: "Commands",
    commandLine: "/{command} — {description}",
    commandDescriptions: {
      start: "start over",
      help: "what I can do",
      settings: "settings",
      today: "today's plan",
      week: "this week's plan",
      deleteme: "delete my data",
      export: "export my data",
    },
    footer: "Everything I remember, you can review, correct and delete.",
  },
  stream: {
    thinking: "Thinking…",
  },
  calendar: {
    back: "‹ Back to calendar",
  },
  demo: {
    paragraphs: [
      "Imagine this is a language model's answer…",
      "It appears on screen gradually, as it is being generated.",
      "You can press Stop at any moment — the generation aborts.",
      "The final answer always arrives as a regular message; the draft disappears.",
    ],
    doneTitle: "Streaming works",
    doneNote: "This is how answers will look once a language model is connected: text appears gradually, and Stop aborts the generation.",
  },
  task: {
    deadline: "Deadline",
    estimate: "Estimate",
    found: "Found time:",
    when: "When",
    confirm: "Book it",
    booked: "✅ Booked",
    copyTime: "Copy time",
    bookedFooter: "I will remind you before it starts.",
    cancelledNote: "Task cancelled.",
    cancelledButton: "Cancelled",
    noSlotsBeforeDeadline: "There is no free time before the deadline. You can pick a time manually or move the deadline.",
    noSlotsHorizon: (days) =>
      `There is no free time in the next ${days === 1 ? "day" : `${days} ${pluralEn(days, "day", "days")}`}. You can pick a time manually.`,
  },
  forward: {
    intro: {
      task: "Looks like a task: “{title}”.",
      meeting: "Looks like “{title}” needs scheduling.",
      reminder: "Looks like you should not forget “{title}”.",
      follow_up: "Looks like a reply is needed about “{title}”.",
    },
    freeTime: "You are free:",
    noSlots: "No free windows yet. You can pick a time manually.",
    info: "There is no task here, it looks like information: “{title}”. Remember it?",
    remember: "Remember",
    rememberNote: "I save it only after you confirm.",
    alternatives: {
      task: "It is a task",
      meeting: "It is a meeting",
      reminder: "Remind me",
      follow_up: "Needs a reply",
      info: "Just remember",
    },
    sourceFrom: "From: {author}",
    sourceHidden: "Forwarded message",
  },
  group: {
    chooserTitle: "What should I do?",
    personal: "Add to my calendar",
    team: "Note it for the group",
    remember: "Just remember",
    rememberNote: "Remembered.",
    teamPending: "Team scheduling is coming soon.",
    pointer: "I prepared the answer in a private chat, where you can also pick a time.",
    openPrivate: "Open private chat",
    found: ["Found a window:", "Found two windows:", "Found three windows:"],
    add: "+ {slot}",
    fromGroup: "Request from the group “{group}”",
  },
  reminder: {
    startsIn: "Starts in {duration}.",
    startsNow: "Time to start.",
    overdue: "The block is already underway or over.",
    when: "When",
    footer: "Cannot make it? Reschedule and I will find another time.",
    reschedule: "Reschedule",
  },
  checkIn: {
    questionTitle: "How did it go?",
    reasonTitle: "What got in the way?",
    outcomes: {
      done: "Done",
      needs_time: "Need more time",
      not_started: "Didn't start",
      blocked: "Something's in the way",
    },
    reasons: {
      not_enough_time: "Not enough time",
      task_too_big: "Task too big",
      unclear_start: "Not sure where to start",
      more_important: "Something more important came up",
      postponed: "Just put it off",
    },
    answeredTitle: "Noted",
    outcome: "Result",
    reason: "Reason",
    recorded: "✅ Recorded",
  },
  settings: {
    title: "Settings",
    workingHours: "Working hours",
    timezone: "Timezone",
    blockLength: "Block length",
    notifications: "Reminders",
    calendar: "Calendar",
    noWorkingDays: "no working days",
    everyDay: "every day",
    hoursValue: "{days}, {from}–{to}",
    intensity: { low: "less often", normal: "normal", high: "more often" },
    calendarConnected: "connected",
    calendarDisconnected: "not connected",
    connectCalendar: "Connect calendar",
    disconnectCalendar: "Disconnect calendar",
    changeHours: "Change working hours",
    openInApp: "Open in the app",
    footer: "Changes apply immediately.",
  },
  notices: {
    expired: "This button has expired. Send your request again and I will find a time.",
    alreadyUsed: "This has already been done.",
    unavailable: "This button is not available. Please start again.",
    unsupportedChat: "That does not work in this chat. Message me privately.",
    slotConflict: "That time is already taken. Pick another.",
    notFound: "I could not find this task. It may have been deleted.",
    transcriptionUnavailable: "I could not understand the voice message. Please write it down.",
    voiceUnavailable: "Voice messages are unavailable right now. Please send text instead.",
    voiceTooLarge: "The voice message is too large. Send a recording under 20 MB or write it down.",
    voiceUnsupported: "This voice format is unsupported. Send OGG/Opus or write it down.",
    intentParserUnavailable: "I cannot read messages right now. Please try again a bit later.",
    invalidTimezone: "I do not know that timezone. Example: Europe/Moscow.",
    failure: "Something went wrong, please try again.",
  },
  inline: {
    slotsTitle: "Free time",
    noSlots: "No free windows found.",
    eventTitle: "Meeting: {title}",
    reminderTitle: "Reminder: {title}",
    when: "When",
    withWho: "With",
    andMore: (count) => `and ${count} more`,
  },
  agenda: {
    today: "Today",
    week: "Week",
    timeColumn: "Time",
    blockColumn: "Block",
    emptyToday: "No blocks today — the day is free.",
    emptyWeek: "No blocks this week.",
    summary: "{blocks} · {duration}",
    statuses: "Status: {done} of {total} done",
    paged: "{title} ({page}/{pages})",
    dayContinued: "{day} (continued)",
  },
  personal: {
    clarifyIntro: "Not sure what this is: “{title}”.",
    clarifyQuestion: "Pick what fits:",
    askTimezone: "Send your timezone, for example Europe/Moscow, or pick one of these.",
    askTaskEdit: "What should I change?",
    askWorkingHours: "Send your working hours, for example “09:00-18:00 Mon-Fri”.",
    timezoneConfirmed: "Timezone saved: {tz}.",
    taskEditNoChange: "Nothing changed.",
    deleteConfirmQuestion: "Delete all my data? This cannot be undone.",
    deleteConfirmYes: "Yes, delete",
    deleteConfirmCancel: "Cancel",
    deleteConfirmed: "Your data was deleted.",
    deleteCancelled: "Cancelled, nothing was deleted.",
  },
};
