import { RU_TIME_WORDS } from "../timeWords";
import { pluralRu } from "./plural";
import type { Catalog } from "./types";

/** Russian copy: the primary locale. */
export const ru: Catalog = {
  time: RU_TIME_WORDS,
  units: {
    blocks: (count) => `${count} ${pluralRu(count, "блок", "блока", "блоков")}`,
  },
  common: {
    quoted: "«{text}»",
    otherTime: "Другое время",
    edit: "Изменить",
    selected: "✓ {label}",
    tryInline: "Свободное время сегодня",
    tryInlineQuery: "свободное время сегодня",
    openMiniApp: "Открыть планировщик",
  },
  welcome: {
    greeting: "Привет!",
    greetingNamed: "Привет, {name}!",
    intro: "Я помогу найти время для задач и поставить его в календарь.",
    ways: [
      "Напиши задачу, например «подготовить презентацию до пятницы, часа на два»",
      "Перешли сообщение — предложу, что с ним сделать",
      "В группе ответь на сообщение и упомяни меня — время подберу только тебе",
    ],
    calendarHint: "Календарь пока не подключён. Подключи его, и я учту твои занятые часы.",
    connectCalendar: "📅 Подключить календарь",
    profileButton: "⚙️ Настроить профиль",
    calendarConnectedNote: "Календарь подключён ✓",
    providersTitle: "Какой календарь подключить?",
    back: "‹ Назад",
    providers: [
      { id: "google", label: "📆 Google" },
      { id: "yandex", label: "🗓 Яндекс" },
      { id: "outlook", label: "📧 Outlook" },
      { id: "apple", label: "🍎 Apple" },
    ],
    legal: "Продолжая пользоваться ботом, вы соглашаетесь с {doc1} и {doc2}.",
    legalDoc1: "документ 1",
    legalDoc2: "документ 2",
  },
  help: {
    title: "Что я умею",
    items: [
      "Личные задачи: напиши, что нужно сделать, — предложу время и поставлю блок в календарь.",
      "Пересланные сообщения: пойму, это встреча, задача или просто информация.",
      "Группы: ответь на сообщение и упомяни меня. Время подберу только тебе, а детали календаря в группе не покажу.",
    ],
    inlineHint: "Быстрый доступ: в любом чате набери {bot} и слова «свободное время».",
    commandsTitle: "Команды",
    commandLine: "/{command} — {description}",
    commandDescriptions: {
      start: "начать заново",
      help: "что я умею",
      settings: "настройки",
      today: "план на сегодня",
      week: "план на неделю",
      deleteme: "удалить мои данные",
      export: "выгрузить мои данные",
    },
    footer: "Всё, что я запоминаю, ты можешь посмотреть, исправить и удалить.",
  },
  stream: {
    thinking: "Думаю…",
  },
  calendar: {
    back: "‹ К календарю",
  },
  demo: {
    paragraphs: [
      "Представь, что это ответ языковой модели…",
      "Он появляется на экране постепенно, по мере генерации.",
      "Кнопку «Стоп» можно нажать в любой момент — генерация прервётся.",
      "Финальный ответ всегда приходит обычным сообщением, черновик исчезает.",
    ],
    doneTitle: "Стриминг работает",
    doneNote: "Так будут выглядеть ответы, когда подключится языковая модель: текст появляется постепенно, «Стоп» отменяет генерацию.",
  },
  task: {
    deadline: "Срок",
    estimate: "Оценка",
    found: "Нашёл время:",
    when: "Когда",
    confirm: "Поставить",
    booked: "✅ Поставлено",
    copyTime: "Скопировать время",
    bookedFooter: "Напомню перед началом.",
    cancelledNote: "Задача отменена.",
    cancelledButton: "Отменено",
    noSlotsBeforeDeadline: "До срока свободного времени не нашлось. Можно выбрать время вручную или сдвинуть срок.",
    noSlotsHorizon: (days) =>
      `${days === 1 ? "В ближайший день" : `В ближайшие ${days} ${pluralRu(days, "день", "дня", "дней")}`} свободного времени нет. Можно выбрать время вручную.`,
  },
  forward: {
    intro: {
      task: "Похоже, это задача: «{title}».",
      meeting: "Похоже, нужно запланировать «{title}».",
      reminder: "Похоже, нужно не забыть про «{title}».",
      follow_up: "Похоже, нужно ответить по теме «{title}».",
    },
    freeTime: "У тебя свободно:",
    noSlots: "Свободных окон пока не нашёл. Можно выбрать время вручную.",
    info: "Здесь нет задачи, это скорее информация: «{title}». Запомнить?",
    remember: "Запомнить",
    rememberNote: "Сохраню только после твоего подтверждения.",
    alternatives: {
      task: "Это задача",
      meeting: "Это встреча",
      reminder: "Напомнить",
      follow_up: "Нужно ответить",
      info: "Просто запомнить",
    },
    sourceFrom: "От: {author}",
    sourceHidden: "Пересланное сообщение",
  },
  group: {
    chooserTitle: "Что сделать?",
    personal: "Мне в календарь",
    team: "Зафиксировать для группы",
    remember: "Просто запомнить",
    rememberNote: "Запомню.",
    teamPending: "Командное планирование скоро будет доступно.",
    pointer: "Ответ подготовил в личных сообщениях — там же можно выбрать время.",
    openPrivate: "Открыть личный чат",
    found: ["Нашёл окно:", "Нашёл два окна:", "Нашёл три окна:"],
    add: "+ {slot}",
    fromGroup: "Запрос из группы «{group}»",
  },
  reminder: {
    startsIn: "Начало через {duration}.",
    startsNow: "Пора начинать.",
    overdue: "Блок уже идёт или закончился.",
    when: "Когда",
    footer: "Не получается? Перенеси, и я подберу другое время.",
    reschedule: "Перенести",
  },
  checkIn: {
    questionTitle: "Как прошло?",
    reasonTitle: "Что помешало?",
    outcomes: {
      done: "Готово",
      needs_time: "Нужно ещё время",
      not_started: "Ещё не начато",
      blocked: "Что-то мешает",
    },
    reasons: {
      not_enough_time: "Не хватило времени",
      task_too_big: "Слишком большая задача",
      unclear_start: "Непонятно, с чего начать",
      more_important: "Появилось более важное",
      postponed: "Отложено",
    },
    answeredTitle: "Записал",
    outcome: "Итог",
    reason: "Причина",
    recorded: "✅ Записано",
  },
  settings: {
    title: "Настройки",
    workingHours: "Рабочие часы",
    timezone: "Часовой пояс",
    blockLength: "Длина блока",
    notifications: "Напоминания",
    calendar: "Календарь",
    noWorkingDays: "нет рабочих дней",
    everyDay: "каждый день",
    hoursValue: "{days}, {from}–{to}",
    intensity: { low: "реже", normal: "обычно", high: "чаще" },
    calendarConnected: "подключён",
    calendarDisconnected: "не подключён",
    connectCalendar: "Подключить календарь",
    disconnectCalendar: "Отключить календарь",
    changeHours: "Изменить рабочие часы",
    openInApp: "Открыть в приложении",
    footer: "Изменения применяются сразу.",
  },
  notices: {
    expired: "Эта кнопка устарела. Напиши запрос заново, и я подберу время.",
    alreadyUsed: "Это действие уже выполнено.",
    unavailable: "Эта кнопка недоступна. Попробуй начать заново.",
    unsupportedChat: "В этом чате так не получится. Напиши мне в личные сообщения.",
    slotConflict: "Это время уже занято. Выбери другое.",
    notFound: "Не нашёл эту задачу — возможно, она уже удалена.",
    transcriptionUnavailable: "Не получилось разобрать голосовое. Напиши текстом, пожалуйста.",
    voiceUnavailable: "Сейчас голосовые сообщения недоступны. Напиши текстом, пожалуйста.",
    voiceTooLarge: "Голосовое слишком большое. Отправь запись до 20 МБ или напиши текстом.",
    voiceUnsupported: "Этот формат голосового не поддерживается. Отправь OGG/Opus или напиши текстом.",
    intentParserUnavailable: "Сейчас не могу разобрать сообщение. Попробуй чуть позже.",
    invalidTimezone: "Не знаю такого часового пояса. Пример: Europe/Moscow.",
    failure: "Что-то пошло не так, попробуй ещё раз.",
  },
  inline: {
    slotsTitle: "Свободное время",
    noSlots: "Свободных окон не нашлось.",
    eventTitle: "Встреча: {title}",
    reminderTitle: "Напомнить: {title}",
    when: "Когда",
    withWho: "С кем",
    andMore: (count) => `и ещё ${count}`,
  },
  agenda: {
    today: "Сегодня",
    week: "Неделя",
    timeColumn: "Время",
    blockColumn: "Блок",
    emptyToday: "На сегодня блоков нет — день свободен.",
    emptyWeek: "На этой неделе блоков нет.",
    summary: "{blocks} · {duration}",
    statuses: "Статусы: {done} из {total} готово",
    paged: "{title} ({page}/{pages})",
    dayContinued: "{day} (продолжение)",
  },
  personal: {
    clarifyIntro: "Не уверен, что это: «{title}».",
    clarifyQuestion: "Выбери, что подходит:",
    askTimezone: "Укажи свой часовой пояс, например Europe/Moscow, или выбери один из вариантов.",
    askTaskEdit: "Что изменить?",
    askWorkingHours: "Напиши рабочие часы, например «09:00-18:00 пн-пт».",
    timezoneConfirmed: "Часовой пояс сохранён: {tz}.",
    taskEditNoChange: "Ничего не изменилось.",
    deleteConfirmQuestion: "Удалить все мои данные? Это нельзя отменить.",
    deleteConfirmYes: "Да, удалить",
    deleteConfirmCancel: "Отмена",
    deleteConfirmed: "Данные удалены.",
    deleteCancelled: "Отменено, данные не удалены.",
  },
};
