import { RU_TIME_WORDS } from "../format";
import { pluralRu } from "./plural";
import type { Catalog } from "./types";

/** Russian copy: the primary locale. */
export const ru: Catalog = {
  time: RU_TIME_WORDS,
  units: {
    days: (count) => `${count} ${pluralRu(count, "день", "дня", "дней")}`,
    blocks: (count) => `${count} ${pluralRu(count, "блок", "блока", "блоков")}`,
  },
  common: {
    quoted: "«{text}»",
    otherTime: "Другое время",
    edit: "Изменить",
    selected: "✓ {label}",
    tryInline: "Свободное время сегодня",
    tryInlineQuery: "свободное время сегодня",
    openMiniApp: "Открыть планировщик",
  },
  welcome: {
    greeting: "Привет!",
    greetingNamed: "Привет, {name}!",
    intro: "Я помогу найти время для задач и поставить его в календарь.",
    ways: [
      "Напиши задачу, например «подготовить презентацию до пятницы, часа на два»",
      "Перешли сообщение — предложу, что с ним сделать",
      "В группе ответь на сообщение и упомяни меня — время подберу только тебе",
    ],
    calendarHint: "Календарь пока не подключён. Подключи его, и я учту твои занятые часы.",
    connectCalendar: "Подключить календарь",
  },
  help: {
    title: "Что я умею",
    items: [
      "Личные задачи: напиши, что нужно сделать, — предложу время и поставлю блок в календарь.",
      "Пересланные сообщения: пойму, это встреча, задача или просто информация.",
      "Группы: ответь на сообщение и упомяни меня. Время подберу только тебе, а детали календаря в группе не покажу.",
    ],
    inlineHint: "Быстрый доступ: в любом чате набери {bot} и слова «свободное время».",
    commandsTitle: "Команды",
    commands: [
      "/settings — настройки",
      "/export — выгрузить мои данные",
      "/deleteme — удалить мои данные",
    ],
    footer: "Всё, что я запоминаю, ты можешь посмотреть, исправить и удалить.",
  },
  task: {
    deadline: "Срок",
    estimate: "Оценка",
    found: "Нашёл время:",
    when: "Когда",
    confirm: "Поставить",
    booked: "✅ Поставлено",
    copyTime: "Скопировать время",
    bookedFooter: "Напомню перед началом.",
    cancelledNote: "Задача отменена.",
    cancelledButton: "Отменено",
    noSlotsBeforeDeadline: "До срока свободного времени не нашлось. Выбери время сам или сдвинь срок.",
    noSlotsHorizon: "В ближайшие {period} свободного времени нет. Можно выбрать время самому.",
  },
  forward: {
    intro: {
      task: "Похоже, это задача: «{title}».",
      meeting: "Похоже, нужно запланировать «{title}».",
      reminder: "Похоже, нужно не забыть про «{title}».",
      follow_up: "Похоже, нужно ответить по теме «{title}».",
    },
    freeTime: "У тебя свободно:",
    noSlots: "Свободных окон пока не нашёл. Можно выбрать время самому.",
    info: "Здесь нет задачи, это скорее информация: «{title}». Запомнить?",
    remember: "Запомнить",
    rememberNote: "Сохраню только после твоего подтверждения.",
    alternatives: {
      task: "Это задача",
      meeting: "Это встреча",
      reminder: "Напомнить",
      follow_up: "Нужно ответить",
      info: "Просто запомнить",
    },
    sourceFrom: "От: {author}",
    sourceHidden: "Пересланное сообщение",
  },
  group: {
    chooserTitle: "Что сделать?",
    personal: "Мне в календарь",
    team: "Зафиксировать для группы",
    remember: "Просто запомнить",
    pointer: "Ответ подготовил в личных сообщениях — там же можно выбрать время.",
    openPrivate: "Открыть личный чат",
    found: ["Нашёл окно:", "Нашёл два окна:", "Нашёл три окна:"],
    add: (day, time) => `Добавить ${day.toLowerCase()} ${time}`,
    fromGroup: "Запрос из группы «{group}»",
  },
  reminder: {
    startsIn: "Начало через {duration}.",
    startsNow: "Пора начинать.",
    when: "Когда",
    footer: "Не получается? Перенеси, и я подберу другое время.",
    reschedule: "Перенести",
  },
  checkIn: {
    questionTitle: "Как прошло?",
    reasonTitle: "Что помешало?",
    outcomes: {
      done: "Готово",
      needs_time: "Нужно ещё время",
      not_started: "Не начал",
      blocked: "Заблокировано",
    },
    reasons: {
      not_enough_time: "Не хватило времени",
      task_too_big: "Слишком большая задача",
      unclear_start: "Не понял, с чего начать",
      more_important: "Появилось более важное",
      postponed: "Просто отложил",
    },
    answeredTitle: "Записал",
    outcome: "Итог",
    reason: "Причина",
    recorded: "✅ Записано",
  },
  settings: {
    title: "Настройки",
    workingHours: "Рабочие часы",
    timezone: "Часовой пояс",
    blockLength: "Длина блока",
    notifications: "Напоминания",
    calendar: "Календарь",
    noWorkingDays: "нет рабочих дней",
    everyDay: "каждый день",
    hoursValue: "{days}, {from}–{to}",
    intensity: { low: "реже", normal: "обычно", high: "чаще" },
    calendarConnected: "подключён",
    calendarDisconnected: "не подключён",
    connectCalendar: "Подключить календарь",
    disconnectCalendar: "Отключить календарь",
    changeHours: "Изменить рабочие часы",
    openInApp: "Открыть в приложении",
    footer: "Изменения применяются сразу.",
  },
  notices: {
    expired: "Эта кнопка устарела. Напиши запрос заново, и я подберу время.",
    alreadyUsed: "Это действие уже выполнено.",
    unavailable: "Эта кнопка недоступна. Попробуй начать заново.",
    unsupportedChat: "В этом чате так не получится. Напиши мне в личные сообщения.",
    slotConflict: "Это время уже занято. Выбери другое.",
    notFound: "Не нашёл эту задачу — возможно, она уже удалена.",
    transcriptionUnavailable: "Не получилось разобрать голосовое. Напиши текстом, пожалуйста.",
    intentParserUnavailable: "Сейчас не могу разобрать сообщение. Попробуй чуть позже.",
    invalidTimezone: "Не знаю такого часового пояса. Пример: Europe/Moscow.",
    failure: "Что-то пошло не так, попробуйте ещё раз.",
  },
  inline: {
    slotsTitle: "Свободное время",
    noSlots: "Свободных окон не нашлось.",
    eventTitle: "Встреча: {title}",
    reminderTitle: "Напомнить: {title}",
    when: "Когда",
    withWho: "С кем",
    andMore: (count) => `и ещё ${count}`,
  },
  agenda: {
    today: "Сегодня",
    week: "Неделя",
    timeColumn: "Время",
    blockColumn: "Блок",
    emptyToday: "На сегодня блоков нет — день свободен.",
    emptyWeek: "На этой неделе блоков нет.",
    summary: "{blocks} · {duration}",
    statuses: "Статусы: {done} из {total} готово",
    paged: "{title} ({page}/{pages})",
    dayContinued: "{day} (продолжение)",
  },
};
